containers:
  dev_env:
    image: "ubuntu:22.04"
    resources:
      memory: "512Mi"
      cpu: "1.0"
    volumes:
      - host_path: "~/lsl_data/dev_env"
        container_path: "/data"
        read_only: false
    network: "host"
    shared: false
    env:
      TZ: "UTC"
      TERM: "xterm-256color"

  web_server:
    image: "nginx:alpine"
    resources:
      memory: "256Mi"
      cpu: "0.5"
    volumes:
      - host_path: "~/lsl_data/web_server"
        container_path: "/usr/share/nginx/html"
        read_only: false
    network: "bridge"
    shared: true
    env:
      NGINX_PORT: "8080"

  shared_terminal:
    image: "ubuntu:22.04"
    resources:
      memory: "256Mi"
      cpu: "0.5"
    volumes:
      - host_path: "~/lsl_data/shared_terminal"
        container_path: "/shared"
        read_only: false
    network: "bridge"
    shared: true
    env:
      TERM: "xterm-256color"
      SESSION_NAME: "shared_session"
